<?php 
$agencyOtherDetails = $this->agencyOtherDetails; 
$certOfTradeDb = $this->certOfTrade;
$recogGovtDb = $this->recogGovt;
//echo '<pre>';
//print_r($this->verifyData);
?>

<div id="dispMessage"><?php if (count($this->messages)) { ?>
        <?php echo ($this->messages[0]); ?>
    <?php } ?> </div>        
<h2 class="col-md-12">Company Details</h2>

<h6 class="col-md-12">Please share some highlights of your company. which you would like to showcase to customers.</h6>
<form id="AgencyMoreAboutCompanyForm" method="POST" enctype="multipart/form-data" action="/register/save-more-about-company" onsubmit="return submitForm();">

    <div class="col-md-12 no-padding">
        <div class="col-md-12">
            <div class="form-group">
                <label>About the Company(250 words maximum)<span class="red">*</span></label>
                <div class="col-md-12 no-padding"><textarea onkeypress="submitForm();" placeholder="About the Company" name="aboutCompany" id="aboutCompany" class="animatedTextArea form-control" ><?php echo trim(@$agencyOtherDetails['AboutUs']); ?></textarea> </div>                   
                <div id="aboutCompanyerr"></div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>

    <div class="col-md-12 no-padding">
        <div class="col-md-6">
            <div class="form-group">
                <label>Certification Of Trade</label>
                <?php $certOfTradeArray = Zend_Controller_Action_HelperBroker::getStaticHelper('General')->getMasterDocumentType(11);
                        //unserialize(AGENCY_CERTIFICATION_OF_TRADE); ?>
                <?php
                if($certOfTradeDb){  $i = 0;
                foreach ($certOfTradeDb as $certOfTrade) { //print_r($certOfTrade);
                    ?>
                    <div class="col-md-12 no-padding">
                        <label class="checkbox disabled">
                            <input class="icheck-red " type="checkbox" name="certOfTrade[<?= $i; ?>]" id="certOfTrade<?= $i; ?>" checked disabled> 
                            <?= trim($certOfTrade['SubTitle']); ?> 
                        </label>

                        <div class="col-md-12 no-padding">
                             &nbsp;&nbsp;<a target="_blank" href="<?php echo $this->baseUrl('public/upload/media/agency/' . @trim(@$this->verifyData['AgencySysId']) . '/' . trim(@$certOfTrade['FilesPath'])); ?>" > Click Here To View</a>
                            <!--&nbsp;&nbsp;<img src="<?php // echo $this->baseUrl('public/upload/media/agency/' . @trim($this->verifyData['AgencySysId']) . '/' . trim($certOfTrade['FilesPath'])); ?>" width="50" height="30"/>-->
                        </div>
                    </div>

                    <?php
                    $i++;
                } }else{
                $i = 0;
                foreach ($certOfTradeArray as $certOfTrade) { //print_r($certOfTrade);
                    ?>
                    <div class="col-md-12 no-padding">
                        <label class="checkbox">
                            <input class="icheck-red certOfTrade" type="checkbox" name="certOfTrade[<?= $i; ?>]" id="certOfTrade<?= $i; ?>" value="<?= trim($certOfTrade['DocType']).'_'.trim($certOfTrade['ParentDocSysId']).'_'.trim($certOfTrade['Title']); ?>"> <?= trim($certOfTrade['Title']); ?> 
                        </label>

                        <div class="col-md-12 no-padding domhdiv" style="display:none;">
                            <input id="certOfTradeFile<?= $i; ?>" name="certOfTradeFile[<?= $i; ?>]" onchange="submitForm();" type="file" class="file whbg" showPreview=false>
                            <div class="error-certOfTrade<?= $i; ?>"></div>
                        </div>
                    </div>

                    <?php
                    $i++;
                }
                }
                ?> 

                <div class="clear"></div></div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label>Recognition from Government</label>
                <?php $recognitionFromGovtArray = Zend_Controller_Action_HelperBroker::getStaticHelper('General')->getMasterDocumentType(15);
//                        unserialize(AGENCY_RECOGNITION_FROM_GOVT); ?>
                <?php
                if($recogGovtDb){  $i = 0;
                foreach ($recogGovtDb as $recognitionFromGovt) { //print_r($certOfTrade);
                    ?>
                    <div class="col-md-12 no-padding">
                        <label class="checkbox disabled">
                            <input class="icheck-red" type="checkbox" name="recognitionFromGovt[<?= $i; ?>]" id="certOfTrade<?= $i; ?>" checked disabled> 
                            <?= trim($recognitionFromGovt['SubTitle']); ?> 
                        </label>

                        <div class="col-md-12 no-padding">
                            &nbsp;&nbsp;<a target="_blank" href="<?php echo $this->baseUrl('public/upload/media/agency/' . @trim(@$this->verifyData['AgencySysId']) . '/' . trim(@$recognitionFromGovt['FilesPath'])); ?>" > Click Here To View</a>
                            <!--&nbsp;&nbsp;<img src="<?php // echo $this->baseUrl('public/upload/media/agency/' . @trim($this->verifyData['AgencySysId']) . '/' . trim($recognitionFromGovt['FilesPath'])); ?>" width="50" height="30"/>-->
                        </div>
                    </div>

                    <?php
                    $i++;
                } }else{
                $i = 0;
                foreach ($recognitionFromGovtArray as $recognitionFromGovt) {
                    ?>
                    <div class="col-md-12 no-padding">
                        <label class="checkbox">
                            <input class="icheck-red" type="checkbox" name="recognitionFromGovt[<?= $i; ?>]" id="recognitionFromGovt<?= $i; ?>" value="<?= trim($recognitionFromGovt['DocType']).'_'.trim($recognitionFromGovt['ParentDocSysId']).'_'.trim($recognitionFromGovt['Title']); ?>"> <?= trim($recognitionFromGovt['Title']); ?> 
                        </label>

                        <div class="col-md-12 no-padding domhdiv" id="domhdiv<?= $i; ?>" style="display:none;">
                            <input id="recognitionFromGovtFile<?= $i; ?>" onchange="submitForm();"  name="recognitionFromGovtFile[<?= $i; ?>]" type="file" class="file whbg recognitionFromGovt" showPreview=false >
                            <div class="error-recognitionFromGovt<?= $i; ?>"></div>
                        </div>

                    </div>

                    <?php
                    $i++;
                }
                }
                ?> 


                <div class="clear"></div></div>
        </div>
    </div>


    <input type="hidden"  name="AgencyId" value="<?php echo $this->verifyData['AgencySysId']; ?>"/>
    <input type="hidden"  name="regEmail" value="<?php echo $this->verifyData['PrimaryEmail']; ?>"/>
    <?php $sessionLogin_user = new Zend_Session_Namespace('AdminUser'); 
    if ((!empty($sessionLogin_user->user))  && empty($this->verifyData['IsApproved']) ) {?>
    <div class="col-md-6">
                    <div class="form-group selDropMess">
                        <label>Select Relationship Manager<?php echo MANDATORY_SIGN; ?></label>
                        <div class="col-md-12 no-padding">
                        <select id="assign_rm" name="assign_rm" class="demo-default select-country" placeholder="Select" maxlength="25">
                            <option value="">Select Relationship Manager</option>
                            <?php foreach ($this->AdminUserList as $AdminUser) { //print_r($AgencyStaff); die; ?> 
                                <option value="<?= $AdminUser['UserSysId']; ?>" <?php echo ($AdminUser['UserSysId'] == $this->rmDetails['UserSysId']) ? 'selected' : ''; ?>><?= ucfirst($AdminUser['UserName']); ?></option>
                            <?php } ?>
                        </select> 
                            </div>
                    </div>
                </div>
    <?php } ?>
    <div class="col-md-12">   
            <div class="form-group form-group1 text-right">
             <?php 
//    $sessionLogin_user       = new Zend_Session_Namespace('sessionLogin_user');
//        if (($sessionLogin_user->intLoggedinUserId == ADMIN_ID)  && empty($this->verifyData['IsApproved']) ) { //condition for admin is same as left navigation in layout 
             
                $this->intLoggedinUserId = $sessionLogin_user->intLoggedinUserId;
                if ((!empty($sessionLogin_user->user))  && empty($this->verifyData['IsApproved']) ) { //condition for admin is same as left navigation in layout ?>
                <img class="loaderimg" style="display: none;" id="loaderimg" src="<?php echo $this->baseUrl('public/images/load1.gif'); ?>"/>
                <a class="button btn btn-warning" id="ApprovedLink" onclick="if(confirm('Are you sure, you want to approve this agency.')){approveAgency('<?php echo $this->verifyData['AgencySysId']; ?>','<?php echo $this->verifyData['PrimaryUserSysId']; ?>');}" >Approve</a>
   <?php  } ?> 
            <input type="submit" class="submit btn btn-info" value="Submit" />
        </div>
    </div>
    

</form>
<!--Advance Radio and checkbox demo start-->
<script src="<?php echo $this->baseUrl('public/assets/js/pages/checkboxRadio.js'); ?>"></script>
<!--Advance Radio and checkbox demo start-->
<script src="<?php echo $this->baseUrl('public/assets/js/pages/selectTag.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl('public/assets/css/plugins/fileinput.min.css'); ?>">

<!--include custom js functions-->
<script src="<?php echo $this->baseUrl('public/js/registrationFunctions.js'); ?>"></script>
<script>

    $('input').on('ifToggled', function () {
        $(this).parent().parent().parent().children(".domhdiv").toggle();
    });

    $(".file").fileinput({
        showUpload: false,
        showRemove: false,
        showUploadedThumbs: false
    });

    $(document).ready(function () {
        $('#dispMessage').delay(3000).fadeOut();
    });

    function submitForm() {
        var aboutCompany = $('#aboutCompany').val();
        var status = 0;
        if (aboutCompany == '') {
            $('#aboutCompanyerr').html('<label class="error1">Please enter some text about your company. </label>')
            status = 1;
        } else {
            $('#aboutCompanyerr').html('');
        }
        
        
        $('input[type=checkbox]').each(function () {  //  loop for all checkboxes
        var sThisVal = (this.checked ? "1" : "0"); //get the value of checked checkbox
        //ids of checkboxes are test1, test2 and ids of files are testFile1,testFile2 so,
       var forFIlename = this.id.replace(/[0-9]/g, '');  // get string from checkbox name
       var counter = this.id.replace(/\D/g, ""); // get counter from checkbox value
       var fileId = forFIlename+'File'+counter;  // prepare file's id
       
//        alert(name+'====='+forFIlename+'==='+fileId);
//        alert($('#'+fileId).val());
        $('.error-'+this.id).html(''); 
        var fileValue = $('#'+fileId).val(); // get value of file by id
        if(fileValue != ''){
         var extension = fileValue.substring(fileValue.lastIndexOf(".")+1).toLowerCase(); // get extension of file in lowercase
         var fileSize = $('#'+fileId)[0].files[0]['size']; // get filesize
        }
        

//        alert(extension+'==='+fileSize);
        if(sThisVal == 1 && fileValue == ''){ // executes when checkbox is checked and file not uploaded 
           $('.error-'+this.id).html('<label class="error1">Please upload required file. </label>').css('display','inline-block'); 
           status = 1;
        } else if(fileValue != '' && $.inArray(extension, ['gif','png','jpg','jpeg']) == -1){ // match with the defined extensions
            $('.error-'+this.id).html('<label class="error1">Please upload valid extension. Ex gif,jpg,png,jpeg. </label>').css('display','inline-block');
           status = 1;
       } else if(fileValue != '' && fileSize > 1048576){ // to check filesize of image
           $('.error-'+this.id).html('<label class="error1">File should be less than 1 MB. </label>').css('display','inline-block');
           status = 1;
       }
      });
           
            if(status === 1){
              return false;  
            } 
            
        return true;
   
        // $("#AgencyMoreAboutCompanyForm").submit();
    }
    
    function approveAgency(agencyid,userId){
        var assign_rm = $('#assign_rm').val();
        if (assign_rm == '') {
            alert('Please select RM');
            return false;
        }
    $.ajax({
        url  : '/register/approve-agency',
       data : { agencyid : agencyid,userId : userId,assign_rm_id : assign_rm},
       dataType : 'html',
       type : 'POST',
       beforeSend: function () {
            $('#loaderimg').css('display', 'inline-block');
            $("#ApprovedLink").attr("disabled", true);
        },
        success: function (response) {            
            if(response == 1){
            registration_process(4);
            $("#ApprovedLink").removeAttr('disabled');
            } else if(response == 3){
              alert('Personal details are required to approve agency.'); 
            } else if(response == 4){
              alert('There has been error in sending email, Please try again later.'); 
            } else {
              alert('There has been error, Please try again later.'); 
            }   
            $('#loaderimg').css('display', 'none');
      } 
    });
    }


</script>
<style>
    .file-preview{
        display:none;
    }
</style>  
