<link rel="stylesheet" href="<?php echo $this->baseUrl('public/assets/css/plugins/validationEngine.jquery.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('public/assets/css/plugins/bootstrapValidator.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('public/assets/css/plugins/fileinput.min.css'); ?>">
<?php //print_r($this->verifyData); die;

if($this->verifyData['IsMobileVerified'] == 1){ ?>
    <h2 class="col-md-12">Your Email ID & Mobile No. are successfully verified<br />
        <span class="orange small"><i class="fa fa-check green"></i> <?php echo $this->verifyData['PrimaryEmail']; ?></span><br/>
        <span class="orange small"><i class="fa fa-check green"></i> <?php echo $this->verifyData['ContactInfo']; ?></span>
    </h2>
    <?php } else{ ?>
    <h2 class="col-md-12">Your Email ID is successfully verified<br />
        <span class="orange small"><i class="fa fa-check green"></i> <?php echo $this->verifyData['PrimaryEmail']; ?></span></h2>

<?php } ?>
    <div style="visibility: hidden;"><!--div is used only for display:none, remove it -->
        <h6 class="col-md-12">Your contact number verification is completed.</h6>
        <div class="col-md-6">
            <div class="form-group">
                <label>Email ID</label>
                <input type="email" class="form-control whbg" value="<?php echo $this->verifyData['PrimaryEmail']; ?>" readonly>                     
            </div>
        </div>


        <div class="col-md-6">
            <div class="form-group">
                <label>Enter OTP</label>
                <input type="email" class="form-control whbg">                     
            </div>
        </div>

    </div>
    <div class="col-md-12">    
        <div class="form-group form-group1 text-right">
            <!--<a href="personalDetails.html" class="btn btn-info"> Verify OTP</a>-->                
            <a href="#" onclick="registration_process(2);return false;" class="btn btn-info"> Next</a> 
        </div>
    </div>

<input type="hidden" name="regEmail" value="<?php echo $this->verifyData['PrimaryEmail']; ?>"/>
    <input type="hidden" name="AgencyId" value="<?php echo $this->verifyData['AgencySysId']; ?>"/>
 <!-- Script For Icheck -->
<script src="<?php echo $this->baseUrl('public/assets/js/icheck.min.js'); ?>"></script>
<!-- Script For Icheck -->
<!--Upload button Script Start-->
<script src="<?php echo $this->baseUrl('public/assets/js/fileinput.min.js'); ?>"></script>
<!--Upload button Script End-->
<!--Advance Radio and checkbox demo start-->
<script src="<?php echo $this->baseUrl('public/assets/js/pages/checkboxRadio.js'); ?>"></script>
<!--Advance Radio and checkbox demo start-->   
<!--include custom js functions-->
<script src="<?php echo $this->baseUrl('public/js/registrationFunctions.js'); ?>"></script>


